export default defineEventHandler(() => {
  return {
    hero: {
      image: '/images/solina4.avif',
      tag: 'Hotel na wodzie',
      title: 'Noc na jeziorze',
    },
    intro: 'Zaśnij kołysany falami Jeziora Solińskiego. Nasze jachty żaglowe to wyjątkowe zakwaterowanie — bez patentu, bez tłumów, z panoramą Bieszczadów tuż za burtą.',
    yachts: [
      {
        id: 'saturn-25',
        name: 'Saturn 25 „Caryńska"',
        tag: 'Flagowy jacht',
        units: 1,
        image: '/images/saturn25-jezero.webp',
        gallery: [
          '/images/saturn25-jezero.webp',
          '/images/saturn25-kokpit.webp',
          '/images/saturn25-kabina.webp',
          '/images/saturn25-salon.webp',
          '/images/saturn25-kuchnia.webp',
        ],
        capacity: 8,
        cabins: 2,
        desc: 'Największy jacht stoczni Saturn Yachts — Saturn 25 „Caryńska". Sportowa linia robi ogromne wrażenie, a dzięki dużemu kokpitowi jest doskonałym wyborem nawet dla większych załóg. Doskonale zrównoważony i bardzo zwrotny. Całe olinowanie sprowadzone do kokpitu umożliwia prowadzenie jachtu nawet jednej osobie. Silnik elektryczny Haswing Vetura 5.0 na pawęży.',
        features: [
          'WC chemiczne na pokładzie',
          'Silnik elektryczny Haswing Vetura 5.0',
          'Kuchenka gazowa',
          'Lodówka',
          'Instalacja wody pitnej z pompą elektryczną',
          'Zlewozmywak + naczynia i akcesoria kuchenne',
          'Instalacja elektryczna 12/220V',
          'Radioodtwarzacz CD',
          'Stolik w kokpicie',
          'Rolfok + Lazy jack',
          'Tent (zadaszenie)',
          'Miecz uchylny',
          'Drabinka rufowa',
          'Środki ratunkowe, pagaj, bosak',
          '4 koje (2 dwuosobowe + 2 jednoosobowe)',
          'Nie wymaga patentu żeglarskiego',
        ],
        pricing: [
          { label: 'Przed sezonem (do 31.05)', value: '430 zł / noc' },
          { label: 'Weekend Majowy (30.04–03.05)', value: '530 zł / noc' },
          { label: 'Sezon przedwakacyjny (1.06–25.06)', value: '480 zł / noc' },
          { label: 'Weekend Boże Ciało (03.06–07.06)', value: '530 zł / noc' },
          { label: 'Sezon wakacyjny (26.06–30.08)', value: '530 zł / noc' },
          { label: 'Sezon powakacyjny (1.09–30.09)', value: '430 zł / noc' },
          { label: 'Październikowe żeglowanie', value: '380 zł / noc' },
        ],
        price: 'od 380 zł / noc',
        specs: [
          { label: 'Długość', value: '7,49 m' },
          { label: 'Szerokość', value: '2,76 m' },
          { label: 'Załoga max', value: '8 osób' },
          { label: 'Wysokość w kabinie', value: '1,72 m' },
          { label: 'Powierzchnia żagli', value: '31 m²' },
          { label: 'Zanurzenie min/max', value: '0,32 / 1,42 m' },
        ],
      },
      {
        id: 'saturn-23',
        name: 'Saturn 23 GT',
        tag: 'Jacht sportowo-turystyczny',
        units: 5,
        image: '/images/saturn23-salon.webp',
        gallery: [
          '/images/saturn23-salon.webp',
          '/images/saturn23-kuchnia.webp',
          '/images/saturn23-wnetrze.webp',
          '/images/saturn23-kokpit.webp',
          '/images/saturn23-plan.webp',
        ],
        capacity: 4,
        cabins: 1,
        desc: 'Sportowa wersja jachtu turystycznego od renomowanej stoczni Saturn Yachts. Nowoczesna linia, ostre kształty i obszerny kokpit — doskonale zrównoważony i bardzo zwrotny, idealny do żeglowania w węższych częściach Soliny. Całe olinowanie sprowadzone do kokpitu umożliwia prowadzenie jachtu nawet jednej osobie. Silnik elektryczny Haswing Vetura 5.0 na pawęży.',
        features: [
          'WC chemiczne na pokładzie',
          'Silnik elektryczny Haswing Vetura 5.0',
          'Kuchenka gazowa',
          'Lodówka',
          'Instalacja wody pitnej z pompą elektryczną',
          'Zlewozmywak + naczynia i akcesoria kuchenne',
          'Instalacja elektryczna 12/220V',
          'Radioodtwarzacz CD',
          'Stolik w kokpicie',
          'Rolfok + Lazy jack',
          'Tent (zadaszenie)',
          'Miecz uchylny',
          'Drabinka rufowa',
          'Środki ratunkowe, pagaj, bosak',
          '4 koje (2 jedno- + 1 dwuosobowa)',
          'Nie wymaga patentu żeglarskiego',
        ],
        pricing: [
          { label: 'Przed sezonem (do 31.05)', value: '380 zł / noc' },
          { label: 'Weekend Majowy (30.04–03.05)', value: '480 zł / noc' },
          { label: 'Sezon przedwakacyjny (1.06–25.06)', value: '430 zł / noc' },
          { label: 'Weekend Boże Ciało (03.06–07.06)', value: '480 zł / noc' },
          { label: 'Sezon wakacyjny (26.06–30.08)', value: '480 zł / noc' },
          { label: 'Sezon powakacyjny (1.09–30.09)', value: '380 zł / noc' },
          { label: 'Październikowe żeglowanie', value: '330 zł / noc' },
        ],
        price: 'od 330 zł / noc',
        specs: [
          { label: 'Długość', value: '6,98 m' },
          { label: 'Szerokość', value: '2,53 m' },
          { label: 'Załoga max', value: '4 osoby' },
          { label: 'Wysokość w kabinie', value: '1,6 m' },
          { label: 'Powierzchnia żagli', value: '24,9 m²' },
          { label: 'Zanurzenie min/max', value: '0,4 / 1,5 m' },
        ],
      },
    ],
    includes: [
      'Pościel i ręczniki',
      'Dostęp do sanitariatów i pryszniców przystani',
      'Obsługa bosmańska',
      'Parking na terenie obiektu',
      'Śniadanie w Tawernie (opcjonalnie)',
      'Możliwość dowozu jedzenia z Tawerny na pokład',
    ],
    note: 'Rezerwacje jachtów przyjmujemy telefonicznie lub mailowo. Minimalna doba hotelowa od godz. 14:00 do 11:00.',
    contact: {
      phone: '+48 691 944 266',
      email: 'przystan@carynska.pl',
    },
  }
})
