export default defineEventHandler(() => {
  return {
    hero: {
      tag: 'Noclegi',
      title: '57 miejsc noclegowych\nnad jeziorem Solina',
      subtitle: 'Pokoje i apartamenty w Polańczyku',
      image: '/images/hotel.png',
    },
    intro: 'Całoroczny ośrodek wypoczynkowo-konferencyjny w Polańczyku oferuje komfortowe zakwaterowanie w pokojach o standardzie podstawowym i podwyższonym oraz apartamentach. Łącznie 67 miejsc noclegowych z możliwością dostawek.',
    rooms: [
      {
        slug: 'pokoj-1-osobowy',
        tag: 'Pokój 1-osobowy',
        title: 'Standard',
        size: '16.85 m²',
        occupancy: 2,
        desc: 'Przytulny pokój z widokiem na jezioro lub góry. Idealne rozwiązanie dla podróżujących solo lub par szukających komfortu w dobrej cenie.',
        amenities: ['Balkon (widok na jezioro lub góry)', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka', 'Suszarka do włosów'],
        image: '/images/solina2.avif',
      },
      {
        slug: 'pokoj-2-osobowy',
        tag: 'Pokój 2-osobowy',
        title: 'Standard',
        size: '15–19 m²',
        occupancy: 3,
        desc: 'Dwa łączone łóżka pojedyncze, balkon i pełne wyposażenie. W wybranych pokojach możliwość dostawki dla trzeciej osoby.',
        amenities: ['Balkon (większość pokoi)', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka', 'Suszarka do włosów'],
        image: '/images/solina3.avif',
      },
      {
        slug: 'pokoj-2-osobowy-plus',
        tag: 'Pokój 2-osobowy',
        title: 'Standard Plus',
        size: '22 m²',
        occupancy: 4,
        desc: 'Strefa dzienna z rozkładaną sofą oraz wydzielona nisza z łóżkiem dwuosobowym. Klimatyzacja ręczna i balkon z widokiem na jezioro lub góry.',
        amenities: ['Balkon z widokiem na jezioro/góry', 'Klimatyzacja ręczna', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka'],
        image: '/images/hotel.png',
      },
      {
        slug: 'studio-3-osobowe',
        tag: 'Studio 3-osobowe',
        title: 'Standard',
        size: '22–26 m²',
        occupancy: 5,
        desc: 'Salon z rozkładaną sofą i sypialnia z dwoma łączonymi łóżkami. Przestronne, rodzinne wnętrze z balkonem w większości jednostek.',
        amenities: ['Balkon (większość)', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka', 'Suszarka do włosów'],
        image: '/images/solina1.avif',
      },
      {
        slug: 'studio-3-osobowe-plus',
        tag: 'Studio 3-osobowe',
        title: 'Standard Plus',
        size: '28 m²',
        occupancy: 5,
        desc: 'Większa wersja studia z balkonem z widokiem na jezioro lub góry. Ten sam układ — wyższy standard wykończenia i piękna panorama.',
        amenities: ['Balkon z widokiem na jezioro/góry', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka', 'Suszarka do włosów'],
        image: '/images/solina4.avif',
      },
      {
        slug: 'apartament-5-osobowy',
        tag: 'Apartament 5-osobowy',
        title: 'Premium',
        size: '40 m²',
        occupancy: 6,
        desc: 'Dwie osobne sypialnie z łączonymi łóżkami i obszerny salon z rozkładaną sofą. Szeroki balkon z panoramicznym widokiem na jezioro lub góry.',
        amenities: ['Szeroki balkon (widok na jezioro/góry)', 'Dwie sypialnie', 'Salon z sofą', 'Łazienka z prysznicem', 'TV + WiFi', 'Czajnik + lodówka'],
        image: '/images/hotel.png',
      },
    ],
    cta: {
      phone: '+48 691 944 266',
      email: 'przystan@carynska.pl',
    },
  }
})
